<a href="https://colab.research.google.com/github/zain4cs/NLP_Project/blob/main/Emotions_NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Datasets/train.txt", sep = ';', header=None, names = ['text', 'emotion'])
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [ ]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

_______________________

**Convert Into Numbers**

In [ ]:
unique_emotions = df['emotion'].unique()

In [ ]:
emotions_numbers = {}
i = 0
for emo in unique_emotions:
  emotions_numbers[emo] = i
  i += 1

df['emotion'] = df['emotion'].map(emotions_numbers)

In [ ]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0
2   im grabbing a minute to post i feel greedy wrong        1
3  i am ever feeling nostalgic about the fireplac...        2
4                               i am feeling grouchy        1

**1: Lower Case**

In [ ]:
df['text'] = df['text'].apply(lambda x: x.lower())

**2: Removing Punctuation**

In [ ]:
import string

def remove_punc(txt):
  return txt.translate(str.maketrans('', '', string.punctuation))

In [ ]:
df['text'] = df['text'].apply(remove_punc)

**3: Remove Numbers**

In [ ]:
def remove_numbers(txt):
  new = ""
  for i in txt:
    if not i.isdigit():
      new = new + i

  return new

df['text'] = df['text'].apply(remove_numbers)

**4: Remove URL/Links**

**5: Remove Emojis**

In [ ]:
def  remove_emojis(txt):
  new = ""
  for i in txt:
    if i.isascii():
      new += i
  return new


df['text'] = df['text'].apply(remove_emojis)

**6: Remove Stopwords**

In [ ]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [ ]:
nltk.download('stopwords')
nltk.download('punkt_tab')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [ ]:
stop_words = set(stopwords.words('english'))
len(stop_words)

198

In [ ]:
# Before
df.loc[1]['text']

'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake'

In [ ]:
def remove(txt):
  # words = word_tokenize(txt)
  words = txt.split()

  cleaned = []
  for i in words:
      if not i in stop_words:
        cleaned.append(i)

  return ' '.join(cleaned)

In [ ]:
df['text'] = df['text'].apply(remove)

In [ ]:
# After
df.loc[1]['text']

'go feeling hopeless damned hopeful around someone cares awake'